### ISSUE TITLE
verbose flag does not provide test case-level results

### ISSUE THREAD

**Issue by yeongk** [cisco/libacvp#452] opened 2020-07-22 14:33 UTC
Used --verbose flag to get the test case-level results, but the output shows only the vector set-level results. How do I get the test case-level test results?

$ app/acvp_app --get_results testSession_97088.json --verbose

***ACVP [STATUS][acvp_login:2355]--> Login successful
***ACVP [INFO][log_network_status:1452]--> GET Vector Set Result...
	Status: 200
	Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions/97088/results
	Resp:
[
  {
    "acvVersion": "1.0"
  },
  {
    "passed": false,
    "results": [
      {
        "vectorSetUrl": "/acvp/v1/testSessions/97088/vectorSets/272845",
        "status": "error"
      },
      {
        "vectorSetUrl": "/acvp/v1/testSessions/97088/vectorSets/272846",
        "status": "passed"
      }
    ]
  }
]

***ACVP [STATUS][acvp_get_result_test_session:2716]--> Test session complete: some vectors failed, reporting results...
***ACVP [STATUS][acvp_get_result_test_session:2717]--> Note: Use verbose-level logging to see results of each test case

My workspace is current as of github commit 8268fa82d5ef233863a7aac1cf6eb5cfe0310521. (Date:   Mon Jul 13 13:55:50 2020 -0400)

**Comment by abkarcher** [comment] 2020-07-22 14:47
Hello,

Libacvp reports the test case results for vector sets that report a status of "fail". A status of "error" would mean there was a problem processing the results on the server end, and you may want to reach out to NIST (https://github.com/usnistgov/ACVP) to get more information on what went wrong if you are getting that error more than once. 

The wording on the output is misleading, and I will make note of that.

Thanks,
Andrew

**Comment by yeongk** [comment] 2020-07-22 14:56
For the vector_upload for this vector sets, I got the following response:

$ app/acvp_app --rsa --vector_upload vector/rsa_acvp_rsp_272845_272846.json --fips_validation metadata/validation.json

***ACVP [STATUS][acvp_upload_vectors_from_file:1017]--> Uploading vectors from response file...
***ACVP [STATUS][acvp_upload_vectors_from_file:1142]--> Sending responses for vector set 272845
***ACVP [STATUS][acvp_upload_vectors_from_file:1142]--> Sending responses for vector set 272846
***ACVP [STATUS][acvp_upload_vectors_from_file:1158]--> Tests complete, checking results...
***ACVP [STATUS][acvp_get_result_test_session:2725]--> TestSession results incomplete...
***ACVP [STATUS][acvp_retry_handler:2283]--> 200 OK results not ready, waiting 30 seconds and trying again...
***ACVP [STATUS][acvp_get_result_test_session:2725]--> TestSession results incomplete...
***ACVP [STATUS][acvp_retry_handler:2283]--> 200 OK results not ready, waiting 30 seconds and trying again...
***ACVP [STATUS][acvp_get_result_test_session:2716]--> Test session complete: some vectors failed, reporting results...
***ACVP [STATUS][acvp_get_result_test_session:2717]--> Note: Use verbose-level logging to see results of each test case
***ACVP [ERR][acvp_validate_test_session:2821]--> This testSession cannot be certified. Required disposition == 'pass'.

**Comment by abkarcher** [comment] 2020-07-23 20:26
Hello,

I have just pushed in a fix that checks for "error" disposition and provides test-case level results. However, there is no guarantee that the nist server will provide the results in this case, as the 'error' disposition (as I mentioned in an issue on the NIST repo) is undocumented. Since I am unable to reproduce this, I have not been able to test.

You can use sample functionality on a new test session (--sample) to get the expected results of test cases as well, to help see if there are any issues processing the test cases. It will automatically print the expected results of any failing vector sets at the end of the session.
I am working on some new functionality that will allow you to get the expected results of sample sessions at will (and save them to a file if desired). It should be available rather soon.

Thanks,
Andrew

**Comment by abkarcher** [comment] 2020-08-07 20:05
Hello,

I am closing this issue as we have provided functionality to query the nist server for test case results in the case of an "error" disposition in our branches for the next release. If other issues arise around this subject, please feel free to create a new one!

In addition, we have added a new API to libacvp (acvp_get_expected_results). 

This is used with acvp_app by using the argument:
--get_expected_results [testSession file]
where the test session has been marked as a sample initially. --get_expected_results can be used alongside:
 --save_to [filename]
 to save the expected results to a file. Otherwise, expected results will be logged.

This new functionality is in the libacvp_1_1_0-throttle and Master branches, and will be included in the next release. Hopefully it can make debugging a bit simpler.

Andrew

**Closed by abkarcher** 2020-08-07 20:05 UTC
